
services:


  saleor-apps-server:
    container_name: saleor-apps-server
    build:
      context: ./saleor-apps-server
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
    restart: unless-stopped
    networks:
      - saleor-backend-tier

  caddy:
    image: caddy:2-alpine
    container_name: saleor-platform-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/data/caddy
    networks:
      - saleor-backend-tier
      

  saleor-app-canada-tax:
    container_name: saleor-app-canada-tax
    build:
      context: ./saleor-apps
      dockerfile: apps/canada-tax/Dockerfile
    restart: unless-stopped
    ports:
      - "3015:3000"
    networks:
      - saleor-network




  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: saleor
      POSTGRES_PASSWORD: saleor
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    networks: [saleor-backend-tier]

  redis:
    image: redis:7.0-alpine
    volumes:
      - saleor-redis:/data
    networks: [saleor-backend-tier]

  jaeger:
    image: jaegertracing/all-in-one
    networks: [saleor-backend-tier]

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: saleor-platform-api
    entrypoint: ["bash", "/app/run-saleor.sh"]
    ports: ["8000:8000"]
    environment:
      DJANGO_SUPERUSER_EMAIL: andrew@amperedigital.ca
      DJANGO_SUPERUSER_PASSWORD: supersecret
    volumes:
      - saleor-media:/app/media
      - ./overrides/settings_patch.py:/app/saleor/settings_patch.py:ro
      - ./run-saleor.sh:/app/run-saleor.sh:ro
      - ./common.env:/app/common.env:ro
      - ./backend.env:/app/backend.env:ro

    depends_on:
      - db
      - redis
      - jaeger
    restart: unless-stopped
    networks: [saleor-backend-tier]

  token-init:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: saleor-platform-token-init
    entrypoint:
      [
        "sh","-c",
        "until curl -sSf http://api:8000/graphql/; do echo waiting for API; sleep 2; done; sh /app/scripts/write-admin-token.sh"
      ]
    environment:
      DJANGO_SUPERUSER_EMAIL: andrew@amperedigital.ca
      DJANGO_SUPERUSER_PASSWORD: supersecret
    volumes:
      - ./scripts/write-admin-token.sh:/app/scripts/write-admin-token.sh:ro
      - ./auth:/app/auth
    depends_on:
      - api
    restart: "no"
    networks: [saleor-backend-tier]

  saleor-app-extension:
    build: ./saleor-app-extension
    container_name: saleor-platform-app-extension
    ports: ["3000:3000"]
    env_file: [./saleor-app-extension/.env]
    volumes:
      - ./auth:/app/auth
    depends_on:
      - api
    restart: unless-stopped
    networks: [saleor-backend-tier]

  dashboard:
    build: ./dashboard
    container_name: saleor-platform-dashboard
    ports: ["9000:80"]
    env_file: [./dashboard/.env]
    depends_on:
      - api
    restart: unless-stopped
    networks: [saleor-backend-tier]

  mailpit:
    image: axllent/mailpit
    container_name: saleor-platform-mailpit
    ports: ["1025:1025","8025:8025"]
    restart: unless-stopped
    networks: [saleor-backend-tier]

volumes:
  saleor-db:
  saleor-redis:
  saleor-media:

networks:
  saleor-backend-tier:
  saleor-network:
    driver: bridge
